# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created: Tue Jan 07 22:09:49 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1012, 895)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 871, 581))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.WelcomeTab = QtGui.QWidget()
        self.WelcomeTab.setObjectName(_fromUtf8("WelcomeTab"))
        self.tabWidget.addTab(self.WelcomeTab, _fromUtf8(""))
        self.DegreeInfoTab = QtGui.QWidget()
        self.DegreeInfoTab.setObjectName(_fromUtf8("DegreeInfoTab"))
        self.comboBox_5 = QtGui.QComboBox(self.DegreeInfoTab)
        self.comboBox_5.setGeometry(QtCore.QRect(10, 10, 131, 22))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.comboBox_5.addItem(_fromUtf8(""))
        self.tabWidget.addTab(self.DegreeInfoTab, _fromUtf8(""))
        self.PlannerTab = QtGui.QWidget()
        self.PlannerTab.setObjectName(_fromUtf8("PlannerTab"))
        self.comboBox = QtGui.QComboBox(self.PlannerTab)
        self.comboBox.setGeometry(QtCore.QRect(20, 10, 101, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox_2 = QtGui.QComboBox(self.PlannerTab)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 40, 101, 22))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_3 = QtGui.QComboBox(self.PlannerTab)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 70, 101, 22))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_4 = QtGui.QComboBox(self.PlannerTab)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 100, 101, 22))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.comboBox_4.addItem(_fromUtf8(""))
        self.label = QtGui.QLabel(self.PlannerTab)
        self.label.setGeometry(QtCore.QRect(180, 140, 91, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.PlannerTab)
        self.label_2.setGeometry(QtCore.QRect(590, 150, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.listView = QtGui.QListView(self.PlannerTab)
        self.listView.setGeometry(QtCore.QRect(10, 170, 411, 381))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.tabWidget.addTab(self.PlannerTab, _fromUtf8(""))
        self.ScheduleTab = QtGui.QWidget()
        self.ScheduleTab.setObjectName(_fromUtf8("ScheduleTab"))
        self.tabWidget.addTab(self.ScheduleTab, _fromUtf8(""))
        self.CalendarTab = QtGui.QWidget()
        self.CalendarTab.setObjectName(_fromUtf8("CalendarTab"))
        self.calendarWidget = QtGui.QCalendarWidget(self.CalendarTab)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 871, 561))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.tabWidget.addTab(self.CalendarTab, _fromUtf8(""))
        self.RecommendedTab = QtGui.QWidget()
        self.RecommendedTab.setObjectName(_fromUtf8("RecommendedTab"))
        self.tabWidget.addTab(self.RecommendedTab, _fromUtf8(""))
        self.ScholarshipTab = QtGui.QWidget()
        self.ScholarshipTab.setObjectName(_fromUtf8("ScholarshipTab"))
        self.textBrowser = QtGui.QTextBrowser(self.ScholarshipTab)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 491, 111))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.ScholarshipTab, _fromUtf8(""))
        self.TransferTab = QtGui.QWidget()
        self.TransferTab.setObjectName(_fromUtf8("TransferTab"))
        self.tabWidget.addTab(self.TransferTab, _fromUtf8(""))
        self.MapTab = QtGui.QWidget()
        self.MapTab.setObjectName(_fromUtf8("MapTab"))
        self.tabWidget.addTab(self.MapTab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1012, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuInfo = QtGui.QMenu(self.menubar)
        self.menuInfo.setObjectName(_fromUtf8("menuInfo"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_File = QtGui.QAction(MainWindow)
        self.actionLoad_File.setObjectName(_fromUtf8("actionLoad_File"))
        self.actionExit_X = QtGui.QAction(MainWindow)
        self.actionExit_X.setObjectName(_fromUtf8("actionExit_X"))
        self.actionDebug = QtGui.QAction(MainWindow)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.actionSave_Schedule_Ctrl_S = QtGui.QAction(MainWindow)
        self.actionSave_Schedule_Ctrl_S.setObjectName(_fromUtf8("actionSave_Schedule_Ctrl_S"))
        self.menuFile.addAction(self.actionSave_Schedule_Ctrl_S)
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addAction(self.actionDebug)
        self.menuFile.addAction(self.actionExit_X)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuInfo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.comboBox_4)
        MainWindow.setTabOrder(self.comboBox_4, self.textBrowser)
        MainWindow.setTabOrder(self.textBrowser, self.calendarWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.WelcomeTab), _translate("MainWindow", "Welcome", None))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Delta College AA/AS", None))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "CSU", None))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "CSU-IGETC", None))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "UC", None))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "UC-IGETC", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DegreeInfoTab), _translate("MainWindow", "Degree Planner", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Year", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "1991-1992", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "1992-1993", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "1993-1994", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "1994-1995", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "1995-1996", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "1996-1997", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "1997-1998", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "1998-1999", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "1999-2000", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "2000-2001", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "2001-2002", None))
        self.comboBox.setItemText(12, _translate("MainWindow", "2002-2003", None))
        self.comboBox.setItemText(13, _translate("MainWindow", "2003-2004", None))
        self.comboBox.setItemText(14, _translate("MainWindow", "2004-2005", None))
        self.comboBox.setItemText(15, _translate("MainWindow", "2005-2006", None))
        self.comboBox.setItemText(16, _translate("MainWindow", "2006-2007", None))
        self.comboBox.setItemText(17, _translate("MainWindow", "2007-2008", None))
        self.comboBox.setItemText(18, _translate("MainWindow", "2008-2009", None))
        self.comboBox.setItemText(19, _translate("MainWindow", "2009-2010", None))
        self.comboBox.setItemText(20, _translate("MainWindow", "2010-2011", None))
        self.comboBox.setItemText(21, _translate("MainWindow", "2011-2012", None))
        self.comboBox.setItemText(22, _translate("MainWindow", "2012-2013", None))
        self.comboBox.setItemText(23, _translate("MainWindow", "2013-2014", None))
        self.comboBox.setItemText(24, _translate("MainWindow", "2014-2015", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Term", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Summer", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Fall", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Spring", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "New Item", None))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "New Item", None))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "New Item", None))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "New Item", None))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "New Item", None))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "New Item", None))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "New Item", None))
        self.label.setText(_translate("MainWindow", "Avaliable Classes", None))
        self.label_2.setText(_translate("MainWindow", "Your Selected Classes", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PlannerTab), _translate("MainWindow", "Schedule Planner", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ScheduleTab), _translate("MainWindow", "Schedule", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CalendarTab), _translate("MainWindow", "Calendar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RecommendedTab), _translate("MainWindow", "Recommended", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">View San Joaquin Delta College\'s Scholarship Application Guide for the 2014-2015 school year </span><a href=\"http://deltacollege.edu/dept/finaid/scholarships/documents/14-15_Schol_Guide_web.pdf\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">here</span></a></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ScholarshipTab), _translate("MainWindow", "Scholarships", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TransferTab), _translate("MainWindow", "Transfer Info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MapTab), _translate("MainWindow", "Map", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuInfo.setTitle(_translate("MainWindow", "Help", None))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File (Ctrl-L)", None))
        self.actionExit_X.setText(_translate("MainWindow", "Exit (Ctrl-X)", None))
        self.actionDebug.setText(_translate("MainWindow", "Debug", None))
        self.actionSave_Schedule_Ctrl_S.setText(_translate("MainWindow", "Save Schedule (Ctrl-S)", None))

